--- #YAML:1.0
name: Yahoo-Marketing
version: 4.01
author:
  - Jeff Lavallee <jeff@zeroclue.com>
abstract: an interface for Yahoo! Search Marketing's Web Services.
license: artistic
generated_by: Module::Build version 0.261, without YAML.pm
